### ISSUE TITLE
Error on generating paper with bibtex

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/Wearables-Research#8]
```
$ bibtex paper
This is BibTeX, Version 0.99d (TeX Live 2015)
The top-level auxiliary file: paper.aux
I couldn't open style file splncs03.bst
---line 16 of file paper.aux
 : \bibstyle{splncs03
 :                   }
I'm skipping whatever remains of this command
I found no \citation commands---while reading file paper.aux
I found no style file---while reading file paper.aux
(There were 3 error messages)
```

**Comment by Glavin001** [comment]
I think running the following will work:

```
pdflatex paper
pdflatex paper
bibtex paper
pdflatex paper
```

Except that `bibtex` will error with the above.

**Comment by mtriff** [comment]
I added the Springer style file that's required, you'll now see the following error when running `bibtex paper` :

```
This is BibTeX, Version 0.99d (TeX Live 2015)
The top-level auxiliary file: paper.aux
The style file: splncs03.bst
I found no \citation commands---while reading file paper.aux
Database file #1: ref.bib
(There was 1 error message)
```

Anytime you add new `\citation`s to the paper, you'll want to run the `bibtex paper` command.  Otherwise if you haven't added any (as it appears is the case now), you don't need to run the command to generate the paper.

**Comment by mtriff** [comment]
Just FYI, I didn't want to interfere with your `master` branch, so I pushed the file to an issue branch `issue8-bibtex`

**Comment by Glavin001** [comment]
Thank you!!! :smiley:
